### ISSUE TITLE
Unidoc directive renders Java links with an extra `?`

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1699]
`@unidoc` renders Java links with an extra `?` in the URL. For example:
- This rendered link: https://doc.akka.io/japi/akka-http/10.0.11/?akka/http/javadsl/server/ExceptionHandler.html
- Should be: https://doc.akka.io/japi/akka-http/10.0.11/akka/http/javadsl/server/ExceptionHandler.html

**Comment by raboof** [comment]
Actually I think the URL is OK, but for 10.0.11 we accidentally published scaladoc also at the javadoc url... https://doc.akka.io/japi/akka-http/10.0.10/?akka/http/javadsl/server/ExceptionHandler.html does work. I *think* this should have been fixed in https://github.com/akka/akka-http/pull/1618 but I'm not entirely clear on it

**Comment by jlprat** [comment]
It makes sense. Then I'll close this one.

**Comment by jrudolph** [comment]
No, I think it is still broken. The links look like this when generated from master:

http://doc.akka.io/japi/akka-http/current/?akka/http/javadsl/server/ExceptionHandler.html

**Comment by jrudolph** [comment]
Ah, I see that's how javadoc works?

**Comment by jrudolph** [comment]
Weird, but why not...

**Comment by jrudolph** [comment]
FTR: With the `?` it open the javadoc with frames, without the `?` it open just the target page.
