### ISSUE TITLE
idle-timeout for server broken when HTTP/2 is enabled

### ISSUE THREAD

**Issue by sumanswaroop** [akka/akka-http#3959]
Package versions:
- openjdk-11-jdk
- scala-2.12.8
- Affected akka-http versions: > 10.1.11. Tested with akka-http-10.2.7, akka-http-10.1.12, akka-http2-support 2.6.17

Configuration:
- http2 enabled
- idle-timeout = 60s

Issue:
if a client establishes a connection to the Akka server and doesn't close it, the TCP connection is not terminated even after idle-timeout seconds. The client just sends the request, reads the response but doesn't close the connection explicitly. The client is still doing some other work.

-  The issue is reproducible when http2 is enabled and akka version is greater than 10.1.11 (I tested with 10.1.15 and 10.2.7).
- Irrespective of the http1.1 or http2 connection type, the issue is reproducible when http2 is enabled in the server.
- If keep alive is disabled, the issue doesn't occur in any version (expected)

Tcpdump analysis:
- After the response is send back to the client, the client sends keep alive packets every 15s.
- In version 10.1.11, connection reset packet is sent by the server after 60s, the same doesn't happen for later versions.

Code to reproduce:
Server:

```
import java.security.{SecureRandom, KeyStore}
import javax.net.ssl.{KeyManagerFactory, SSLContext, TrustManagerFactory}
import akka.http.scaladsl.{HttpsConnectionContext, ConnectionContext}
import akka.http.scaladsl.server.Route

import akka.http.scaladsl.settings.ParserSettings
import akka.http.scaladsl.settings.ParserSettings.ErrorLoggingVerbosity
import akka.http.scaladsl.settings.RoutingSettings
import akka.http.scaladsl.settings.ServerSettings

import akka.stream.ActorMaterializerSettings
import akka.stream.ActorMaterializer

import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.stream.ActorMaterializer
import com.typesafe.config.ConfigFactory
import akka.http.scaladsl.server.RoutingLog

import scala.concurrent.Await
import scala.util.{Failure, Success}

object Main extends App {
  val serverContext: HttpsConnectionContext = {
    val password = "abcdef".toCharArray
    val context = SSLContext.getInstance("TLS")
    val ks = KeyStore.getInstance("PKCS12")
    ks.load(getClass.getClassLoader.getResourceAsStream("abc.p12"), password)
    val keyManagerFactory = KeyManagerFactory.getInstance("SunX509")
    keyManagerFactory.init(ks, password)
    val tmf: TrustManagerFactory = TrustManagerFactory.getInstance("SunX509")
    tmf.init(ks)
     context.init(keyManagerFactory.getKeyManagers, tmf.getTrustManagers, new SecureRandom)
    ConnectionContext.httpsServer(context)
  }

  val host = "0.0.0.0"
  val port = 9000

  val customconfig = ConfigFactory.parseString("""
    akka.loglevel = DEBUG
    akka.http {
        server {
            idle-timeout = 60 s
            socket-options {
            so-reuse-address = true
            tcp-no-delay = false
            }
        }
    }
    akka.http.server.preview.enable-http2 = true
    """)

  private val config = ConfigFactory.load(customconfig)
  val http2Status =
    config.getBoolean("akka.http.server.preview.enable-http2")
  println(s"HTTP2 is $http2Status")
  val idletimeout = config.getString("akka.http.server.idle-timeout")
  println(s"idle timeout is $idletimeout")
  
  implicit val system: ActorSystem = ActorSystem(name = "todoapi", config)
  implicit val materializer: ActorMaterializer = ActorMaterializer()
  import system.dispatcher
  
  import akka.http.scaladsl.server.Directives._
  def route = path("check") {
    get {
      complete("Response!")
    }
  }

  val binding = Http().newServerAt(interface=host, port=port).enableHttps(serverContext).bind(route)
  binding.onComplete {
    case Success(_) => println("Success!")
    case Failure(error) => println(s"Failed: ${error.getMessage}")
  }

  import scala.concurrent.duration._
  Await.result(binding, 3.seconds)
```

A bad client:
```
import (
        "fmt"
        "io"
        "io/ioutil"
        "net/http"
        "os"
        "time"
		"crypto/tls"
)

func main() {
		tr := &http.Transport{}
		tr.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
		client := &http.Client{Transport: tr}
                resp, err := client.Get("https://<ip>:9000/check")
                if err != nil {
                        fmt.Fprintf(os.Stderr, "fetch: %v\n", err)
                        os.Exit(1)
                }
                _, err = io.Copy(ioutil.Discard, resp.Body)
                resp.Body.Close()
                if err != nil {
                        fmt.Fprintf(os.Stderr, "fetch: reading: %v\n", err)
                        os.Exit(1)
                }
               for {
                      fmt.Fprintf(os.Stderr, "minute\n")
                      time.Sleep(60 * time.Second)
               }
}
```

build.sbt
```
name := "akkahttp"
version := "0.1"
scalaVersion := "2.12.8"
libraryDependencies ++= Seq("com.typesafe.akka" %% "akka-actor" % "2.6.17",  "com.typesafe.akka" %% "akka-stream" % "2.6.17",  "com.typesafe.akka" %% "akka-http" % "10.2.7", "com.typesafe.akka" %% "akka-http2-support" % "10.2.7")
```

**Comment by jrudolph** [comment]
Thanks for the comprehensive report, @sumanswaroop. Can you check if this behavior is specific to HTTPS connections? We previously had issues with the TLS implementation getting stuck in such a situation.

**Comment by sumanswaroop** [comment]
I removed the enableHttps method call in the code and tried with an HTTP connection. Unfortunately, the issue was still there.

**Comment by jrudolph** [comment]
Thanks, I reproduced the issue. The problem is that when HTTP/2 is enabled, the server setup is a different one and then the idle timeout is not applied.

**Comment by sumanswaroop** [comment]
@jrudolph Thanks for the quick fix. When is the version with the fix planned to be released?

**Comment by jrudolph** [comment]
There's no planned date yet, since we just released a new version. But you can try the latest snapshot in the meantime: https://doc.akka.io/docs/akka-http/current/contributing.html#snapshots

**Comment by sumanswaroop** [comment]
@jrudolph Do you have a plan to back port this fix to any older versions?

**Comment by raboof** [comment]
> @jrudolph Do you have a plan to back port this fix to any older versions?

We typically don't backport changes to previous versions unless they're particularly important, like security fixes. While some Akka satellite projects still have a transitive dependency on Akka HTTP 10.1, because of our [binary compatibility rules](https://doc.akka.io/docs/akka-http/current/compatibility-guidelines.html) you can update to Akka HTTP 10.2 in your project to get access to the fixes.
